<div class="block-social on_right hidden-sm hidden-xs">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social')->toHtml();?>
</div>
<div class="header-container">
	<div class="top-link-container">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 top-bar">
					<?php echo $this->getChildHtml("store_switcher"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("currency"); ?>
					<span class="txt-welcome">
						<?php echo $this->helper('Rokanthemes\RokanBase\Helper\Data')->getConfigData('design/header/welcome'); ?>
					</span>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 end-top-bar">
					 <?php //echo $this->getChildHtml("top.search"); ?>
					 <?php //echo $this->getChildHtml("minicart");?>
					 <?php echo $this->getChildHtml("top_link"); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="header">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3 col-xs-12 col-logo">
					<?php echo $this->getChildHtml("logo"); ?>
				</div>
				<div class="col-md-9 col-sm-9 col-xs-12 col-search">
					<?php echo $this->getChildHtml("minicart");?>
					<?php echo $this->getChildHtml("topSearch");?>
					<?php echo $this->getChildHtml("top.search"); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="nav-menus">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 wraper-main-nav">
					<div class="visible-xs visible-sm icon-menu-bar">
						<div class="toggle-action">
							<div class="menu-line"></div>
							<div class="menu-line"></div>
							<div class="menu-line"></div>
						</div>
					</div>
                    <?php echo $this->getChildHtml( 'top.navigation.sections' ); ?>
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mobile-nav')->toHtml();?>
<!--					--><?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-nav')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if ($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()): ?>
<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function($){
        	var screenWidth = $(window).width();
        	var num = $('.header-container').outerHeight();
        	var flag = true;
			function scrollSticky() {
				$(window).scroll(function() {
					if ($(this).scrollTop() > num && screenWidth >= 991 ){
						$(".header-container").addClass("sticky");
						$('.side-verticalmenu').removeClass('open');
						var width_container = $(".header-container .container").outerWidth();
						var fixed_right = (screenWidth - width_container) / 2;
						$(".header-container.sticky .minicart-wrapper").css('right', fixed_right+'px');
					}else if( $(this).scrollTop() <= num && screenWidth >= 991 ){
						$(".header-container").removeClass("sticky");
						$('.cms-index-index .side-verticalmenu').addClass('open');
						$(".header-container .minicart-wrapper").css('right', 'initial');
					}else {
						$(".header-container").removeClass("sticky");
					}

				});
			}
			scrollSticky();

			$(window).resize(function(){
				screenWidth = $(window).width();
        		scrollSticky();
        	});

		});
    });
</script>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function($){
    		var widthMobile = $(window).width();
	    	if ( widthMobile < 991 ) {
				$('.side-verticalmenu').removeClass('open');
			}
        });
	});
</script>