<ul class="top-link">
	<?php if($this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()): ?>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/logout');?>"><?php echo __('Logout');?></a></li>	
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/'); ?>"><?php echo __('My account') ?></a></li>
	<?php else: ?>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/'); ?>"><?php echo __('My account') ?></a></li>
	<?php endif ?>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('giftr/index/index'); ?>"><?php echo __('Gift Registry') ?></a></li>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('store-locator'); ?>"><?php echo __('Store Locator') ?></a></li>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('checkout/cart/'); ?>"><?php echo __('Checkout') ?></a></li>
</ul>