<?php $_brands = $block->getBrandsCollection(); ?>
<ul class="brands-owl-carousel owl-nav-beside">
    <?php foreach ($_brands as $_brand): ?>
    <?php foreach ($_brands as $brand): ?>
        <li>
            <a href="<?= $_brand->getUrl() ?>" title="<?= $_brand->getName() ?>">
                <img src="<?= $_brand->getImageUrl('brand_logo') ?>" alt="<?= $_brand->getName() ?>">
            </a>
        </li>
    <?php endforeach; ?>
    <?php endforeach; ?>
</ul>

<script type="text/javascript">
    require([
        'jquery',
        'mage/mage',
        'rokanthemes/owl'
    ], function ($) {
        'use strict';

        jQuery(document).ready(function () {
            jQuery(".brands-owl-carousel").owlCarousel({
                autoPlay: true,
                items: 10,
                itemsDesktop: [1199, 10],
                itemsDesktopSmall: [980, 8],
                itemsTablet: [768, 6],
                itemsMobile: [479, 3],
                slideSpeed: 500,
                paginationSpeed: 500,
                rewindSpeed: 500,
                navigation: true,
                stopOnHover: true,
                pagination: false,
                scrollPerPage: true,
            });
        });
    });
</script>