
<div class="top-content-home">
	<div class="section-delivery">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('delivery')->toHtml();?>
		</div>
	</div>
    <div class="banner-top-home hidden-xs">
        <div class="container">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top')->toHtml();?>
        </div>
    </div>
    <div class="section-product-tab">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\ProductTab\Block\Producttab')->setTemplate('Rokanthemes_ProductTab::producttab.phtml')->toHtml();?> 
		</div>
	</div>
	<div class="box-banner-middle">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle')->toHtml();?>
		</div>
	</div>
	<div class="section-category-tab category-tab-1">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cat1_slider')->toHtml();?>
		</div>
	</div>
    <div class="section-category-tab category-tab-2">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cat2_slider')->toHtml();?>
		</div>
	</div>

	<div class="box-banner-middle box-banner-middle-2">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle2')->toHtml();?>
		</div>
	</div>

	<div class="group-product">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?>
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml();?> 
				</div>
				<div class="col-md-4 col-xs-12">
					<?php echo $block->getLayout()->createBlock('Rokanthemes\MostviewedProduct\Block\Mostviewed')->setTemplate('Rokanthemes_MostviewedProduct::mostviewed.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>

	<div class="section-brands">
		<div class="container">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('section_brands')->toHtml(); ?>
		</div>
	</div>
	<!--
	<div class="section_testimonial">
		<div class="container">
			<?php /*echo $block->getLayout()->createBlock('Rokanthemes\Testimonial\Block\Testimonial')->setTemplate('Rokanthemes_Testimonial::testimonial.phtml')->toHtml();*/?>
		</div>
	</div>
	-->
    <div class="section-services">
		<div class="container">
			<div class="support-footer-inner">
				<div class="row">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('section_services')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>